# Generated by Django 5.2.4 on 2025-11-07 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='break_duration',
            field=models.DurationField(blank=True, help_text='Expected break duration at this stop (for food/rest stops)', null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='facilities',
            field=models.JSONField(blank=True, default=dict, help_text="Available facilities at this stop (e.g., {'restroom': true, 'restaurant': true})"),
        ),
        migrations.AddField(
            model_name='routestop',
            name='is_food_stop',
            field=models.BooleanField(default=False, help_text='This is a designated food/refreshment stop'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='notes',
            field=models.TextField(blank=True, help_text='Special instructions or notes for this stop'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='price_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Price multiplier for this stop segment', max_digits=3, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='routestop',
            name='stop_type',
            field=models.CharField(choices=[('regular', 'Regular Stop'), ('food', 'Food/Rest Stop'), ('fuel', 'Fuel Stop'), ('emergency', 'Emergency Stop')], default='regular', help_text='Type of stop', max_length=20),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='is_dropoff',
            field=models.BooleanField(default=True, help_text='Passengers can alight here'),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='is_pickup',
            field=models.BooleanField(default=True, help_text='Passengers can board here'),
        ),
    ]
